name: Generate index.md
on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate index.md
        shell: pwsh
        run: ./scripts/generate-index.ps1
