name: Generate index.md
on:
  push:

env:
  filename: "index.md"

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Generate ${{ env.filename }}"
        shell: pwsh
        run: ./scripts/generate-index.ps1
      - name: "Commit ${{ env.filename }}"
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Adding ${{ env.filename }}"
          git push
